//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Customer_CustomerWorkspace
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CustomerWorkspaceID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerWorkspace CustomerWorkspace { get; set; }
    }
}
