//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CR_Customer_CustomerWorkspace = new HashSet<CR_Customer_CustomerWorkspace>();
            this.CustomerAddress = new HashSet<CustomerAddress>();
            this.CustomerPhone = new HashSet<CustomerPhone>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int Status { get; set; }
        public int CreatorUID { get; set; }
        public string CreatorIP { get; set; }
        public string CreatorRole { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> UpdatorUID { get; set; }
        public string UpdatorIP { get; set; }
        public string UpdatorRole { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Customer_CustomerWorkspace> CR_Customer_CustomerWorkspace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPhone> CustomerPhone { get; set; }
    }
}
