//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWorkspace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerWorkspace()
        {
            this.CR_Customer_CustomerWorkspace = new HashSet<CR_Customer_CustomerWorkspace>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int CreatorUID { get; set; }
        public string CreatorIP { get; set; }
        public string CreatorRole { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Customer_CustomerWorkspace> CR_Customer_CustomerWorkspace { get; set; }
    }
}
